---
server.port: 8001
jasypt:
  encryptor:
    algorithm: PBEWithHmacSHA256AndAES_128
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
spring:
  application:
    name: wishlist
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration-postgre
  #  datasource:
#    username: system
#    password: oracle
#    url: jdbc:oracle:thin:@localhost:32988:xe
  datasource:
    url: jdbc:postgresql://ec2-63-35-156-160.eu-west-1.compute.amazonaws.com:5432/da9e4viav6mhqv?user=pajulknpxnwcfp&password=e9afae34e08fd8760aa3ca88639b25199a3ba126f623f2d229c365f4cd9fc5ce&currentSchema=public
    driver-class-name: org.postgresql.Driver
    max-active: 10
    max-idle: 5
    min-idle: 2
    initial-size: 5
    remove-abandoned: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: qqqq54227@gmail.com
    password: ENC(13XtFFZKxsWxjNa7D8MBnUv6XFNuvLBXZGK5O3iPAnELtEpaNAXnYmNrbSR150JrOMauyWPXEaliH+S7cH3/Sw==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
templates:
  path: /email/templates/
jira:
  username: anton.bazavluk@gmail.com
  password: ATATT3xFfGF0DK9_kMiKKV2ZYOELcq4FuXZz2hh_BV-Ht583LQDndj4N2RjJOfNi1lgYrXcymlDHlqHzHQshIlNB86qDRRMdyRRfRuLe0xSBbHD_0E8JC1BPfAS8iJVJujggdkscyKyRrVP94rHkV9JXfcaLV1ootTICqopzw0rDmvmEdsAehGw=5D992BA4
  url: https://getficha.atlassian.net
