---
server.port: 8001
spring:
  application:
    name: wishlist
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    username: system
    password: oracle
    url: jdbc:oracle:thin:@localhost:32988:xe