---
server.port: 8001
jasypt:
  encryptor:
    algorithm: PBEWithHmacSHA256AndAES_128
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
spring:
  application:
    name: wishlist
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration-postgre
    #logging.level.ru.raiffeisen.wishlist.config.FeignConfig: DEBUG
#    datasource:
#    username: system
#    password: oracle
#    url: jdbc:oracle:thin:@localhost:32988:xe
  datasource:
    url: jdbc:postgresql://ec2-63-35-156-160.eu-west-1.compute.amazonaws.com:5432/da9e4viav6mhqv?user=pajulknpxnwcfp&password=e9afae34e08fd8760aa3ca88639b25199a3ba126f623f2d229c365f4cd9fc5ce&currentSchema=public
    driver-class-name: org.postgresql.Driver
    max-active: 10
    max-idle: 5
    min-idle: 2
    initial-size: 5
    remove-abandoned: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: qqqq54227@gmail.com
    password: ENC(13XtFFZKxsWxjNa7D8MBnUv6XFNuvLBXZGK5O3iPAnELtEpaNAXnYmNrbSR150JrOMauyWPXEaliH+S7cH3/Sw==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
templates:
  path: /email/templates/
jira:
  username: anton.bazavluk@gmail.com
  password: ENC(QyVe2Ec9sUxdRQXBFX2qqxZXV+GqIfPfeJbFV/G0ZTJnDWHHQvTQNJYEdttAyftu1t0hgOwjjMKtmPskNlJXmNRdh+/Q1+AShWXB9FdZEeZeZ+XBloflih/Rynz5qZOCiXjczb/Kyw8ZMymnQ6pI4WVucNOAtbGolp5UDGjSxDLbRTtn/o7OEdskwI58l7Y10ChO6amGLR2kyCRznX2VjOBNfO4K1MirlnJooU64cMmWuFLjRkmMLfAqelQLbOFCZNK0H+mInHXpbvub57WqzIUAD5KWgPULhsPzjt6pCDcndCuljyWvtI6MQqJWgKSc)
  url: https://getficha.atlassian.net
feign:
  client:
    config:
      jiraClient:
        loggerLevel: FULL